/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movie.ticket;

import db.dbconnection;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SUNNY
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        this.setLocation(160, 90);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jButton1 = new javax.swing.JButton();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Userupd = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        Bookt = new javax.swing.JInternalFrame();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        Bookh = new javax.swing.JInternalFrame();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        About = new javax.swing.JInternalFrame();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        ctick = new javax.swing.JInternalFrame();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        tcd = new javax.swing.JInternalFrame();
        kGradientPanel7 = new keeptoo.KGradientPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Cpass = new javax.swing.JInternalFrame();
        kGradientPanel8 = new keeptoo.KGradientPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jPasswordField5 = new javax.swing.JPasswordField();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(153, 153, 153));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseReleased(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Multiply_25px.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 30, 30));

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Male_User_100px_2.png"))); // NOI18N
        kGradientPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, 120));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sign Out ?");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        kGradientPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 140, 30));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 19)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kGradientPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 30));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Update Profile");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        kGradientPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 210, 30));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Book a Ticket");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        kGradientPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 210, 30));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Booking History");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        kGradientPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 210, 30));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        kGradientPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 140, 30));

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Delete Your Account");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
        });
        kGradientPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 210, 30));

        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 1, 17)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Theater Contact Details");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel30MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel30MouseExited(evt);
            }
        });
        kGradientPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 210, 30));

        kGradientPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 590));

        Userupd.setClosable(true);
        Userupd.setVisible(false);
        Userupd.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("E-mail:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("UserName:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Mobile:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Answer:");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Password:");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 150, -1));

        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel5.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 150, -1));

        jTextField4.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel5.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 310, -1));

        jTextField5.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel5.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 150, -1));

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Question.", "What is the name of your previous school ?", "In which City or Town your nearest sibling live ?", "What is the name of your most favourite vedio game of all the time ?" }));
        jPanel5.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 490, -1));

        jPasswordField3.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPasswordField3.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPasswordField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField3KeyReleased(evt);
            }
        });
        jPanel5.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 150, -1));

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Security Question:");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(0, 0, 0));
        jTextField6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel5.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 150, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 255));
        jButton5.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        jButton7.setBackground(new java.awt.Color(0, 0, 255));
        jButton7.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(0, 0, 0));
        jTextField7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel5.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 150, -1));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Customer ID:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jButton8.setBackground(new java.awt.Color(0, 0, 255));
        jButton8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Change Password");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, -1));

        Userupd.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 350));

        kGradientPanel1.add(Userupd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 710, 370));

        Bookt.setClosable(true);
        Bookt.setVisible(false);
        Bookt.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel3.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel3.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Movie Timmings:");
        kGradientPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 160, 30));

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("No. of Seats:");
        kGradientPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 140, 30));

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Movie Name:");
        kGradientPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 150, 30));

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 0, 17)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kGradientPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 120, 30));

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Movie Date:");
        kGradientPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 120, 30));

        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Comic Sans MS", 0, 17)); // NOI18N
        jDateChooser1.setInheritsPopupMenu(true);
        jDateChooser1.setMaxSelectableDate(new java.util.Date(253370748715000L));
        kGradientPanel3.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 180, -1));

        jComboBox2.setFont(new java.awt.Font("Comic Sans MS", 0, 17)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        kGradientPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 180, 30));

        jComboBox3.setFont(new java.awt.Font("Comic Sans MS", 0, 17)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        kGradientPanel3.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 180, 30));

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 0, 17)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        kGradientPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 70, 30));

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Total Price:");
        kGradientPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 110, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 17)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("About this movie");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 170, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 17)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Confirm Ticket");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        kGradientPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Theater Name:");
        kGradientPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 150, 30));

        jComboBox4.setFont(new java.awt.Font("Comic Sans MS", 0, 17)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });
        kGradientPanel3.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 180, 30));

        Bookt.getContentPane().add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 490));

        kGradientPanel1.add(Bookt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 620, 510));

        Bookh.setClosable(true);
        Bookh.setVisible(false);
        Bookh.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel4.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel4.setkStartColor(new java.awt.Color(102, 102, 102));
        kGradientPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));

        jTable1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Theater Name", "Movie name", "Movie time", "Movie date", "No.of seats", "Total price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        kGradientPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 350));

        Bookh.getContentPane().add(kGradientPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 348));

        kGradientPanel1.add(Bookh, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 620, 370));

        About.setClosable(true);
        About.setVisible(false);
        About.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel5.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel5.setkStartColor(new java.awt.Color(102, 102, 102));
        kGradientPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));
        kGradientPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 20, 170, 160));

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 520, 20));

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Description :");
        kGradientPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 190, 90, -1));

        jLabel27.setBackground(new java.awt.Color(102, 102, 102));
        jLabel27.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel27.setOpaque(true);
        jScrollPane2.setViewportView(jLabel27);

        kGradientPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 620, 140));

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Available in :");
        kGradientPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 90, 20));

        jButton4.setBackground(new java.awt.Color(0, 0, 255));
        jButton4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Ok");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        kGradientPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, -1, -1));

        About.getContentPane().add(kGradientPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 450));

        kGradientPanel1.add(About, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 620, 470));

        ctick.setClosable(true);
        ctick.setVisible(false);
        ctick.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel6.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel6.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kGradientPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 50, 20));

        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Password:");
        kGradientPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 255));
        jButton6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Confirm");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        kGradientPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField1.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        kGradientPanel6.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 120, -1));

        ctick.getContentPane().add(kGradientPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 240));

        kGradientPanel1.add(ctick, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 490, -1));

        tcd.setClosable(true);
        tcd.setVisible(false);
        tcd.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel7.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel7.setkStartColor(new java.awt.Color(102, 102, 102));
        kGradientPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBackground(new java.awt.Color(102, 102, 102));

        jTable2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Theater Name", "Website", "Contact Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        kGradientPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 350));

        tcd.getContentPane().add(kGradientPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 348));

        kGradientPanel1.add(tcd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 620, 370));

        Cpass.setClosable(true);
        Cpass.setVisible(false);
        Cpass.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel8.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel8.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Confirm Password:");
        kGradientPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel33.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("New Password:");
        kGradientPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel34.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Old Password:");
        kGradientPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jPasswordField2.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPasswordField2.setCaretColor(new java.awt.Color(255, 255, 255));
        kGradientPanel8.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 170, -1));

        jPasswordField4.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPasswordField4.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPasswordField4.setCaretColor(new java.awt.Color(255, 255, 255));
        kGradientPanel8.add(jPasswordField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 170, -1));

        jPasswordField5.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPasswordField5.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPasswordField5.setCaretColor(new java.awt.Color(255, 255, 255));
        kGradientPanel8.add(jPasswordField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 170, -1));

        jButton9.setBackground(new java.awt.Color(0, 0, 255));
        jButton9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Change");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        kGradientPanel8.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        Cpass.getContentPane().add(kGradientPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 338));

        kGradientPanel1.add(Cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 400, 360));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int xx, xy;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(new Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Multiply_25px_1.png")));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(new Color(204, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Multiply_25px.png")));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        jButton1.setBackground(new Color(204, 0, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        jButton1.setBackground(new Color(0, 0, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseReleased

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
        setOpacity((float) 0.5);
        xx = evt.getX();
        xy = evt.getY();         // TODO add your handling code here:
    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);         // TODO add your handling code here:
    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void kGradientPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseReleased
        setOpacity(((float) 1.0));        // TODO add your handling code here:
    }//GEN-LAST:event_kGradientPanel1MouseReleased

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setForeground(new Color(0, 0, 255));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        jLabel9.setForeground(new Color(0, 0, 255));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setForeground(new Color(0, 0, 255));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel8.setForeground(new Color(0, 0, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        jLabel9.setForeground(new Color(0, 0, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setForeground(new Color(0, 0, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int j = JOptionPane.showConfirmDialog(this, "Are you sure?", "Confirmation", 0, 2);
        if (j == 0) {
            new MovieTicket1().setVisible(true);;
            this.dispose();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jPasswordField3.setText("");// TODO add your handling code here:
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jComboBox1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (jTextField2.getText().equals("") || jComboBox1.getSelectedIndex() == 0 || jTextField7.getText().equals("") || jTextField4.getText().equals("") || jTextField3.getText().equals("") || jTextField6.getText().equals("") || jTextField5.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Fill all details to update profile");
        } else {
            try {
                String mail = jTextField3.getText();
                String mob = jTextField5.getText();
                Object que = jComboBox1.getSelectedItem();
                String nque = String.valueOf(que);
                String nans = jTextField4.getText();
                String cid = jTextField7.getText();
                dbconnection d = new dbconnection();
                d.pstmt = d.con.prepareCall("UPDATE usereg SET Mail = '" + mail + "',Mob = '" + mob + "',SECURITY = '" + nque + "',Answer = '" + nans + "' WHERE cid = '" + cid + "'");
                int j = d.pstmt.executeUpdate();
                if (j > 0) {
                    JOptionPane.showMessageDialog(this, "Profile Updated Succesfully");
                    jButton5ActionPerformed(evt);
                }
            } // TODO add your handling code here:
            catch (Exception e) {
                e.getMessage();
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        try {
            tcd.setVisible(false);
            Bookh.setVisible(false);
            Userupd.setVisible(true);
            Bookt.setVisible(false);
            jPasswordField3.setText("");
            jTextField4.setText("");
            jComboBox1.setSelectedIndex(0);
            dbconnection d = new dbconnection();// TODO add your handling code here:
            d.stmt = d.con.createStatement();
            d.rst = d.stmt.executeQuery("Select cid,Name,Mail,Username,Mob from usereg where Name='" + jLabel4.getText() + "'");
            while (d.rst.next()) {
                jTextField7.setText(d.rst.getString(1));
                jTextField2.setText(d.rst.getString(2));
                jTextField3.setText(d.rst.getString(3));
                jTextField6.setText(d.rst.getString(4));
                jTextField5.setText(d.rst.getString(5));
            }
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jPasswordField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField3KeyReleased
        try {
            dbconnection d = new dbconnection();
            d.stmt = d.con.createStatement();
            d.rst = d.stmt.executeQuery("Select Pass from usereg where Name='" + jLabel4.getText() + "'");
            while (d.rst.next()) {
                if (jPasswordField3.getText().equals(d.rst.getString(1))) {
                    d.rst = d.stmt.executeQuery("Select Security from usereg where Name='" + jLabel4.getText() + "'");
                    if (d.rst.next()) {
                        jComboBox1.setSelectedItem(d.rst.getString(1));
                    }
                }
            }
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_jPasswordField3KeyReleased

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        int j = JOptionPane.showConfirmDialog(this, "Are you sure?", "Confirmation", 0, 2);
        if (j == 0) {
            MovieTicket1 m = new MovieTicket1();
            m.setVisible(true);
            this.dispose();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setForeground(new Color(0, 0, 255));
        jLabel2.setForeground(new Color(0, 0, 255));// TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setForeground(new Color(0, 0, 0));
        jLabel2.setForeground(new Color(0, 0, 0));// TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel5.setForeground(new Color(0, 0, 255));
        jLabel2.setForeground(new Color(0, 0, 255)); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel5.setForeground(new Color(0, 0, 0));
        jLabel2.setForeground(new Color(0, 0, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        int j = JOptionPane.showConfirmDialog(this, "You will no longer access this account", "Warning", 2, 0);
        if (j == 0) {
            try {
                dbconnection d = new dbconnection();
                d.pstmt = d.con.prepareStatement("delete  FROM usereg WHERE Name ='" + jLabel4.getText() + "'");// TODO add your handling code here:
                int f = d.pstmt.executeUpdate();
                d.pstmt = d.con.prepareStatement("delete  FROM book WHERE User ='" + jLabel4.getText() + "'");// TODO add your handling code here:
                int u = d.pstmt.executeUpdate();
                d.pstmt = d.con.prepareStatement("delete  FROM imgu WHERE uname ='" + jLabel4.getText() + "'");// TODO add your handling code here:
                int i = d.pstmt.executeUpdate();
                if (f > 0 || u > 0 || i > 0) {
                    JOptionPane.showMessageDialog(this, "Your account deleted successfully");
                    MovieTicket1 m = new MovieTicket1();
                    m.setVisible(true);
                    this.dispose();
                }
            } catch (Exception e) {
                e.getMessage();
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        jLabel18.setForeground(new Color(0, 0, 255));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseEntered

    private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
        jLabel18.setForeground(new Color(0, 0, 0));  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        try {
            DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
            mod.getDataVector().removeAllElements();
            tcd.setVisible(false);
            Bookh.setVisible(true);
            Userupd.setVisible(false);
            Bookt.setVisible(false);
            dbconnection d = new dbconnection();
            d.stmt = d.con.createStatement();
            d.rst = d.stmt.executeQuery("Select * from book where User='" + jLabel4.getText() + "'");
            while (d.rst.next()) {
                Object content[] = {d.rst.getString(2), d.rst.getString(3), d.rst.getString(4), d.rst.getString(5), d.rst.getString(6), d.rst.getString(7)};
                mod.addRow(content);
            }
        }// TODO add your handling code here:
        catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        try {jComboBox4.removeAllItems();
            tcd.setVisible(false);
            Bookh.setVisible(false);
            Userupd.setVisible(false);
            Bookt.setVisible(true);
            jDateChooser1.setDate(null);
            jTextField1.setText("");
            jLabel21.setText("");
            jComboBox4.addItem("Select Theater");
            dbconnection d = new dbconnection();
            d.stmt = d.con.createStatement();
            d.rst = d.stmt.executeQuery("Select theatername from theatereg");
            while (d.rst.next()) {
                jComboBox4.addItem(d.rst.getString(1));
            }
        } catch (Exception e) {
            e.getMessage();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        try {
            jComboBox3.removeAllItems();
            jComboBox3.addItem("Select Movie Name");
            dbconnection d = new dbconnection();
            d.stmt = d.con.createStatement();
            d.rst = d.stmt.executeQuery("Select DISTINCT movname from addmov where theater ='" + jComboBox4.getSelectedItem() + "'");
            while (d.rst.next()) {
                jComboBox3.addItem(d.rst.getString(1));
            }
        } // TODO add your handling code here:
        catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        try {
            jComboBox2.removeAllItems();
            jComboBox2.addItem("Select Movie Timming");
            dbconnection d = new dbconnection();
            d.stmt = d.con.createStatement();
            d.rst = d.stmt.executeQuery("Select movtim from addmov where movname='" + jComboBox3.getSelectedItem() + "'AND theater='" + jComboBox4.getSelectedItem() + "'");// TODO add your handling code here:
            while (d.rst.next()) {
                jComboBox2.addItem(d.rst.getString(1));
            }
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        try {
            dbconnection d = new dbconnection();
            d.stmt = d.con.createStatement();
            d.rst = d.stmt.executeQuery("Select movsdat,movedate from addmov where movname='" + jComboBox3.getSelectedItem() + "'AND theater='" + jComboBox4.getSelectedItem() + "'");// TODO add your handling code here:
            if (d.rst.next()) {
                jDateChooser1.setSelectableDateRange(d.rst.getDate(1), d.rst.getDate(2));
            }
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged
    byte[] im;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        try {
            String ava = "";
            dbconnection d = new dbconnection();
            d.stmt = d.con.createStatement();
            d.rst = d.stmt.executeQuery("Select movdes,movpos from addmov where movname='" + jComboBox3.getSelectedItem() + "'AND theater='" + jComboBox4.getSelectedItem() + "'");
            if (d.rst.next()) {
                jLabel27.setText(d.rst.getString(1));
                im = d.rst.getBytes(2);
                Image j = new ImageIcon(im).getImage();
                Image k = j.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
                jLabel3.setIcon(new ImageIcon(k));
            }
            d.rst = d.stmt.executeQuery("Select distinct theater from addmov where movname='" + jComboBox3.getSelectedItem() + "'");
            while (d.rst.next()) {
                ava = ava + d.rst.getString(1) + ", ";
                jLabel25.setText(ava);
            }
            About.setVisible(true);
            Bookt.setVisible(false);
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        About.setVisible(false);
        Bookt.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        try {
            dbconnection d = new dbconnection();
            d.stmt = d.con.createStatement();
            d.rst = d.stmt.executeQuery("Select movpri from addmov where movname='" + jComboBox3.getSelectedItem() + "'AND theater='" + jComboBox4.getSelectedItem() + "'And movtim='" + jComboBox2.getSelectedItem() + "'");// TODO add your handling code here:
            if (d.rst.next()) {
                jLabel21.setText(String.valueOf(d.rst.getInt(1) * Integer.parseInt(jTextField1.getText())));
            }
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i;
        ctick.setVisible(true);
        Bookt.setVisible(false);
//        
//        for (i = 60; i >= 0; i--) {
//            
//            try{
//            Thread.sleep(1000);
//            }
//            catch(Exception e)
//            {
//                
//            }
//            if(i==0)
//            {
//               JOptionPane.showMessageDialog(this,"Your Session Expired..!!");
//               Bookt.setVisible(true);
//               ctick.setVisible(false);
//            }
//        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            dbconnection d = new dbconnection();
            d.stmt = d.con.createStatement();
            d.rst = d.stmt.executeQuery("Select pass from usereg where Name='" + jLabel4.getText() + "'");// TODO add your handling code here:
            if (d.rst.next()) {
                if (d.rst.getString(1).equals(jPasswordField1.getText())) {
                    d.pstmt = d.con.prepareStatement("INSERT INTO book(User,theater,movnam,movtim,movdat,seat,tpric)VALUES (?,?,?,?,?,?,?)");
                    d.pstmt.setString(1, jLabel4.getText());
                    d.pstmt.setString(2, String.valueOf(jComboBox4.getSelectedItem()));
                    d.pstmt.setString(3, String.valueOf(jComboBox3.getSelectedItem()));
                    d.pstmt.setString(4, String.valueOf(jComboBox2.getSelectedItem()));
                    d.pstmt.setString(5, ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText());
                    d.pstmt.setString(6, jTextField1.getText());
                    d.pstmt.setString(7, jLabel21.getText());
                    int f = d.pstmt.executeUpdate();
                    if (f > 0) {
                        JOptionPane.showMessageDialog(this, "Booking Confirmed");
                        jPasswordField1.setText("");
                        Bookt.setVisible(true);
                        jComboBox4.setSelectedIndex(0);
                        jComboBox4.setSelectedIndex(-1);
                        jComboBox4.setSelectedIndex(-1);
                        jDateChooser1.setDate(null);
                        jTextField1.setText("");
                        jLabel21.setText("");
                        ctick.setVisible(false);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Password Incorrect");
                }
            }
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel30MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseEntered
        jLabel30.setForeground(new Color(0, 0, 255));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseEntered

    private void jLabel30MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseExited
        jLabel30.setForeground(new Color(0, 0, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseExited

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        try {
            DefaultTableModel t = (DefaultTableModel) jTable2.getModel();
            t.getDataVector().removeAllElements();
            Bookh.setVisible(false);
            Userupd.setVisible(false);
            Bookt.setVisible(false);
            tcd.setVisible(true);
            dbconnection d = new dbconnection();
            d.stmt = d.con.createStatement();
            d.rst = d.stmt.executeQuery("SELECT theatername,website,cno FROM theatereg");
            while (d.rst.next()) {
                Object content[] = {d.rst.getString(1), d.rst.getString(2), d.rst.getString(3)};
                t.addRow(content);
            }
        }// TODO add your handling code here:
        catch (Exception e) {
            e.getMessage();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Cpass.setVisible(true);
        Userupd.setVisible(false);
        jPasswordField2.setText("");
        jPasswordField4.setText("");
        jPasswordField5.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            dbconnection d = new dbconnection();
            d.stmt = d.con.createStatement();
            d.rst = d.stmt.executeQuery("SELECT Pass FROM usereg where Name='" + jLabel4.getText() + "'");
            if (d.rst.next()) {
                if (jPasswordField5.getText().equals(d.rst.getString(1))) {
                    if (jPasswordField2.getText().equals(jPasswordField4.getText())) {
                        d.pstmt = d.con.prepareStatement("UPDATE usereg SET Pass = '" + jPasswordField2.getText() + "' WHERE Name='" + jLabel4.getText() + "'");
                        int g = d.pstmt.executeUpdate();
                        if (g > 0) {
                            JOptionPane.showMessageDialog(this, "Password Changed");
                            jPasswordField2.setText("");
                            jPasswordField4.setText("");
                            jPasswordField5.setText("");
                            Cpass.setVisible(false);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Retype the passwords");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Old Password Incorrect");
                }
            }
        } catch (Exception e) {
            e.getMessage();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame About;
    private javax.swing.JInternalFrame Bookh;
    private javax.swing.JInternalFrame Bookt;
    private javax.swing.JInternalFrame Cpass;
    private javax.swing.JInternalFrame Userupd;
    private javax.swing.JInternalFrame ctick;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel6;
    private keeptoo.KGradientPanel kGradientPanel7;
    private keeptoo.KGradientPanel kGradientPanel8;
    private javax.swing.JInternalFrame tcd;
    // End of variables declaration//GEN-END:variables
}
